# Generated by Django 4.0.6 on 2022-08-18 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_ans', models.CharField(max_length=50)),
                ('word', models.CharField(max_length=50)),
                ('meaning', models.CharField(max_length=50)),
                ('en_sentence', models.CharField(max_length=10000000)),
                ('jp_sentence', models.CharField(max_length=10000000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('meaning', models.CharField(max_length=50)),
                ('en_sentence', models.CharField(max_length=10000000)),
                ('jp_sentence', models.CharField(max_length=10000000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
