# Generated by Django 4.0.5 on 2022-08-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correct_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_id', models.CharField(max_length=1000000000)),
            ],
        ),
    ]
