# Generated by Django 4.0.5 on 2022-08-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_correct_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='cnt_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='cnt_wrong',
            field=models.IntegerField(default=0),
        ),
    ]
