# Generated by Django 4.0.5 on 2022-08-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_correct_id_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ans_choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_id', models.CharField(max_length=50)),
                ('question_id', models.CharField(max_length=50)),
            ],
        ),
    ]
